services:
  db:
    image: postgres:16
    container_name: toolDBContainer
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: toolDB
    ports:
      - "5434:5432"
    volumes:
      - ./migrations/001-init:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
